Fix aspnet-s2i template. (#22)
Do not specify the app to match in the selector/labels.
For some reason the used parameter is not consistently
replaced by the same value, hence the error:

"""
error: DeploymentConfig "aspnet-app" is invalid:
spec.template.metadata.labels: Invalid value:
{"app":"aspnet-s2i","deploymentconfig":"aspnet-app"}:
selector does not match template labels
"""

For the DeploymentConfig section in the template the
app label turns out to be aspnet-s2i (the template name)
and not the parameter value, aspnet-app. Hence the
mismatch. Work around that by not specifying the
app label and by not specifying the app in the selector.

Closes issue #13